name: Build Customer Service

on:
  push:
    branches:
      - master
    paths:
      - "**"
      - "customer_service/**"
      - "!.idea/**"
      - "!service_registration/**"
      - "!auth/**"
      - "!common/**"
      - "!content_service/**"
      - "!gateway/**"
      - "!streaming_service/**"
      - "!.github/workflows/**"
      - ".github/workflows/customerservice-workflow.yml"
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Maven Package
        run: mvn -B clean package -DskipTests --file customer_service/pom.xml
      - name: Maven Verify
        run: mvn -B clean verify --file customer_service/pom.xml
      - name: Build artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: customer_service/target/customer_service-1.0-SNAPSHOT.jar
      - name: run scan
        run: sonar-scanner
          -Dsonar.host.url=http://34.91.252.251:9000
          -Dsonar.projectKey=flixned-customerservice
          -Dsonar.sources=./customer_service/src/main/java
          -Dsonar.java.binaries=./customer_service/target

  deployment:
    runs-on: ubuntu-latest
    needs: test
    env:
      REPO: ${{ secrets.DOCKERHUB_CUSTOMERSERVICE}}
    steps:
      - uses: actions/checkout@v2
      - name: Download Maven build artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: build
        run: |
          mkdir -p customer_service/target
          mv artifact/customer_service-1.0-SNAPSHOT.jar customer_service/target
          docker build -f customer_service/Dockerfile -t flixned customer_service
      - name: Tags
        run: |
          docker tag flixned ${{ secrets.DOCKER_USER }}/$REPO:${GITHUB_SHA::8}
          docker tag flixned ${{ secrets.DOCKER_USER }}/$REPO:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/$REPO